var ccMathStructure = [  
   {  
      "name":"Kindergarten",
      "strands":[  
         {  
            "name":"Counting",
            "code":"cc",
            "clusters":[  
               {  
                  "name":"Counting",
                  "standards":[  
                     {  
                        "code":"k.cc.1"
                     },
                     {  
                        "code":"k.cc.2"
                     },
                     {  
                        "code":"k.cc.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Quantity",
                  "standards":[  
                     {  
                        "code":"k.cc.4",
                        "children":[  
                           {  
                              "code":"k.cc.4a"
                           },
                           {  
                              "code":"k.cc.4b"
                           },
                           {  
                              "code":"k.cc.4c"
                           }
                        ]
                     },
                     {  
                        "code":"k.cc.5"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Compare numbers",
                  "standards":[  
                     {  
                        "code":"k.cc.6"
                     },
                     {  
                        "code":"k.cc.7"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Road to Algebra",
            "code":"oa",
            "clusters":[  
               {  
                  "name":"Addition and subtraction",
                  "standards":[  
                     {  
                        "code":"k.oa.1"
                     },
                     {  
                        "code":"k.oa.2"
                     },
                     {  
                        "code":"k.oa.3"
                     },
                     {  
                        "code":"k.oa.4"
                     },
                     {  
                        "code":"k.oa.5"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Place Value",
            "code":"nbt",
            "clusters":[  
               {  
                  "name":"Place value foundation",
                  "standards":[  
                     {  
                        "code":"k.nbt.1"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Measurement and Data",
            "code":"md",
            "clusters":[  
               {  
                  "name":"Compare objects",
                  "standards":[  
                     {  
                        "code":"k.md.1"
                     },
                     {  
                        "code":"k.md.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Sorting",
                  "standards":[  
                     {  
                        "code":"k.md.3"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Shapes",
                  "standards":[  
                     {  
                        "code":"k.g.1"
                     },
                     {  
                        "code":"k.g.2"
                     },
                     {  
                        "code":"k.g.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Compare, create, and compose",
                  "standards":[  
                     {  
                        "code":"k.g.4"
                     },
                     {  
                        "code":"k.g.5"
                     },
                     {  
                        "code":"k.g.6"
                     }
                  ],
                  "index":"b"
               }
            ]
         }
      ]
   },
   {  
      "name":"1<sup>st</sup> Grade",
      "strands":[  
         {  
            "name":"",
            "code":"",
            "clusters":[  

            ]
         },
         {  
            "name":"Road to Algebra",
            "code":"oa",
            "clusters":[  
               {  
                  "name":"Addition and subtraction problems",
                  "standards":[  
                     {  
                        "code":"1.oa.1"
                     },
                     {  
                        "code":"1.oa.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Understand addition and subtraction",
                  "standards":[  
                     {  
                        "code":"1.oa.3"
                     },
                     {  
                        "code":"1.oa.4"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Fluency in addition and subtraction",
                  "standards":[  
                     {  
                        "code":"1.oa.5"
                     },
                     {  
                        "code":"1.oa.6"
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"Equations and unknowns",
                  "standards":[  
                     {  
                        "code":"1.oa.7"
                     },
                     {  
                        "code":"1.oa.8"
                     }
                  ],
                  "index":"d"
               }
            ]
         },
         {  
            "name":"Place Value",
            "code":"nbt",
            "clusters":[  
               {  
                  "name":"Counting",
                  "standards":[  
                     {  
                        "code":"1.nbt.1"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Understanding place value",
                  "standards":[  
                     {  
                        "code":"1.nbt.2",
                        "children":[  
                           {  
                              "code":"1.nbt.2a"
                           },
                           {  
                              "code":"1.nbt.2b"
                           },
                           {  
                              "code":"1.nbt.2c"
                           }
                        ]
                     },
                     {  
                        "code":"1.nbt.3"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Addition and subtraction",
                  "standards":[  
                     {  
                        "code":"1.nbt.4"
                     },
                     {  
                        "code":"1.nbt.5"
                     },
                     {  
                        "code":"1.nbt.6"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Measurement and Data",
            "code":"md",
            "clusters":[  
               {  
                  "name":"Length measurement",
                  "standards":[  
                     {  
                        "code":"1.md.1"
                     },
                     {  
                        "code":"1.md.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Tell and write time",
                  "standards":[  
                     {  
                        "code":"1.md.3"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Data",
                  "standards":[  
                     {  
                        "code":"1.md.4"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Shapes",
                  "standards":[  
                     {  
                        "code":"1.g.1"
                     },
                     {  
                        "code":"1.g.2"
                     },
                     {  
                        "code":"1.g.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         }
      ]
   },
   {  
      "name":"2<sup>nd</sup> Grade",
      "strands":[  
         {  
            "name":"",
            "code":"",
            "clusters":[  

            ]
         },
         {  
            "name":"Road to Algebra",
            "code":"oa",
            "clusters":[  
               {  
                  "name":"Addition and subtraction problems",
                  "standards":[  
                     {  
                        "code":"2.oa.1"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Fluency in addition and subtraction",
                  "standards":[  
                     {  
                        "code":"2.oa.2"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Equal groups of objects",
                  "standards":[  
                     {  
                        "code":"2.oa.3"
                     },
                     {  
                        "code":"2.oa.4"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Place Value",
            "code":"nbt",
            "clusters":[  
               {  
                  "name":"Place value within 1000",
                  "standards":[  
                     {  
                        "code":"2.nbt.1",
                        "children":[  
                           {  
                              "code":"2.nbt.1a"
                           },
                           {  
                              "code":"2.nbt.1b"
                           }
                        ]
                     },
                     {  
                        "code":"2.nbt.2"
                     },
                     {  
                        "code":"2.nbt.3"
                     },
                     {  
                        "code":"2.nbt.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Addition and subtraction",
                  "standards":[  
                     {  
                        "code":"2.nbt.5"
                     },
                     {  
                        "code":"2.nbt.6"
                     },
                     {  
                        "code":"2.nbt.7"
                     },
                     {  
                        "code":"2.nbt.8"
                     },
                     {  
                        "code":"2.nbt.9"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Measurement and Data",
            "code":"md",
            "clusters":[  
               {  
                  "name":"Lengths in standard units",
                  "standards":[  
                     {  
                        "code":"2.md.1"
                     },
                     {  
                        "code":"2.md.2"
                     },
                     {  
                        "code":"2.md.3"
                     },
                     {  
                        "code":"2.md.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Add and subtract lengths",
                  "standards":[  
                     {  
                        "code":"2.md.5"
                     },
                     {  
                        "code":"2.md.6"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Time and money",
                  "standards":[  
                     {  
                        "code":"2.md.7"
                     },
                     {  
                        "code":"2.md.8"
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"Data",
                  "standards":[  
                     {  
                        "code":"2.md.9"
                     },
                     {  
                        "code":"2.md.10"
                     }
                  ],
                  "index":"d"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Shapes",
                  "standards":[  
                     {  
                        "code":"2.g.1"
                     },
                     {  
                        "code":"2.g.2"
                     },
                     {  
                        "code":"2.g.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         }
      ]
   },
   {  
      "name":"3<sup>rd</sup> Grade",
      "strands":[  
         {  
            "name":"Fractions",
            "code":"nf",
            "clusters":[  
               {  
                  "name":"Fractions as numbers",
                  "standards":[  
                     {  
                        "code":"3.nf.1"
                     },
                     {  
                        "code":"3.nf.2",
                        "children":[  
                           {  
                              "code":"3.nf.2a"
                           },
                           {  
                              "code":"3.nf.2b"
                           }
                        ]
                     },
                     {  
                        "code":"3.nf.3",
                        "children":[  
                           {  
                              "code":"3.nf.3a"
                           },
                           {  
                              "code":"3.nf.3b"
                           },
                           {  
                              "code":"3.nf.3c"
                           },
                           {  
                              "code":"3.nf.3d"
                           }
                        ]
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Road to Algebra",
            "code":"oa",
            "clusters":[  
               {  
                  "name":"Multiplication and division",
                  "standards":[  
                     {  
                        "code":"3.oa.1"
                     },
                     {  
                        "code":"3.oa.2"
                     },
                     {  
                        "code":"3.oa.3"
                     },
                     {  
                        "code":"3.oa.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Understand multiplication and division",
                  "standards":[  
                     {  
                        "code":"3.oa.5"
                     },
                     {  
                        "code":"3.oa.6"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Multiply and divide fluently",
                  "standards":[  
                     {  
                        "code":"3.oa.7"
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"All four operations",
                  "standards":[  
                     {  
                        "code":"3.oa.8"
                     },
                     {  
                        "code":"3.oa.9"
                     }
                  ],
                  "index":"d"
               }
            ]
         },
         {  
            "name":"Place Value",
            "code":"nbt",
            "clusters":[  
               {  
                  "name":"Multi-digit arithmetic",
                  "standards":[  
                     {  
                        "code":"3.nbt.1"
                     },
                     {  
                        "code":"3.nbt.2"
                     },
                     {  
                        "code":"3.nbt.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Measurement and Data",
            "code":"md",
            "clusters":[  
               {  
                  "name":"Measurement",
                  "standards":[  
                     {  
                        "code":"3.md.1"
                     },
                     {  
                        "code":"3.md.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Data",
                  "standards":[  
                     {  
                        "code":"3.md.3"
                     },
                     {  
                        "code":"3.md.4"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Area",
                  "standards":[  
                     {  
                        "code":"3.md.5",
                        "children":[  
                           {  
                              "code":"3.md.5a"
                           },
                           {  
                              "code":"3.md.5b"
                           }
                        ]
                     },
                     {  
                        "code":"3.md.3"
                     },
                     {  
                        "code":"3.md.7",
                        "children":[  
                           {  
                              "code":"3.md.7a"
                           },
                           {  
                              "code":"3.md.7b"
                           },
                           {  
                              "code":"3.md.7c"
                           },
                           {  
                              "code":"3.md.7d"
                           }
                        ]
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"Perimeter",
                  "standards":[  
                     {  
                        "code":"3.md.8"
                     }
                  ],
                  "index":"d"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Shapes",
                  "standards":[  
                     {  
                        "code":"3.g.1"
                     },
                     {  
                        "code":"3.g.2"
                     }
                  ],
                  "index":"a"
               }
            ]
         }
      ]
   },
   {  
      "name":"4<sup>th</sup> Grade",
      "strands":[  
         {  
            "name":"Fractions",
            "code":"nf",
            "clusters":[  
               {  
                  "name":"Understanding fractions",
                  "standards":[  
                     {  
                        "code":"4.nf.1"
                     },
                     {  
                        "code":"4.nf.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Unit fractions",
                  "standards":[  
                     {  
                        "code":"4.nf.3",
                        "children":[  
                           {  
                              "code":"4.nf.3a"
                           },
                           {  
                              "code":"4.nf.3b"
                           },
                           {  
                              "code":"4.nf.3c"
                           },
                           {  
                              "code":"4.nf.3d"
                           }
                        ]
                     },
                     {  
                        "code":"4.nf.4",
                        "children":[  
                           {  
                              "code":"4.nf.4a"
                           },
                           {  
                              "code":"4.nf.4b"
                           },
                           {  
                              "code":"4.nf.4c"
                           }
                        ]
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Decimal notation to hundredths",
                  "standards":[  
                     {  
                        "code":"4.nf.5"
                     },
                     {  
                        "code":"4.nf.6"
                     },
                     {  
                        "code":"4.nf.7"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Road to Algebra",
            "code":"oa",
            "clusters":[  
               {  
                  "name":"Four operations",
                  "standards":[  
                     {  
                        "code":"4.oa.1"
                     },
                     {  
                        "code":"4.oa.2"
                     },
                     {  
                        "code":"4.oa.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Factors and multiples",
                  "standards":[  
                     {  
                        "code":"4.oa.4"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Patterms",
                  "standards":[  
                     {  
                        "code":"4.oa.5"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Place Value",
            "code":"nbt",
            "clusters":[  
               {  
                  "name":"Understand place value",
                  "standards":[  
                     {  
                        "code":"4.nbt.1"
                     },
                     {  
                        "code":"4.nbt.2"
                     },
                     {  
                        "code":"4.nbt.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Multi-digit operations",
                  "standards":[  
                     {  
                        "code":"4.nbt.4"
                     },
                     {  
                        "code":"4.nbt.5"
                     },
                     {  
                        "code":"4.nbt.6"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Measurement and Data",
            "code":"md",
            "clusters":[  
               {  
                  "name":"Measurement",
                  "standards":[  
                     {  
                        "code":"4.md.1"
                     },
                     {  
                        "code":"4.md.2"
                     },
                     {  
                        "code":"4.md.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Data",
                  "standards":[  
                     {  
                        "code":"4.md.4"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Angles",
                  "standards":[  
                     {  
                        "code":"4.md.5",
                        "children":[  
                           {  
                              "code":"4.md.5a"
                           },
                           {  
                              "code":"4.md.5b"
                           }
                        ]
                     },
                     {  
                        "code":"4.md.6"
                     },
                     {  
                        "code":"4.md.7"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Geometry foundations",
                  "standards":[  
                     {  
                        "code":"4.g.1"
                     },
                     {  
                        "code":"4.g.2"
                     },
                     {  
                        "code":"4.g.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         }
      ]
   },
   {  
      "name":"5<sup>th</sup> Grade",
      "strands":[  
         {  
            "name":"Fractions",
            "code":"nf",
            "clusters":[  
               {  
                  "name":"Addition and subtraction",
                  "standards":[  
                     {  
                        "code":"5.nf.1"
                     },
                     {  
                        "code":"5.nf.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Multiplication and division",
                  "standards":[  
                     {  
                        "code":"5.nf.3"
                     },
                     {  
                        "code":"5.nf.4",
                        "children":[  
                           {  
                              "code":"5.nf.4a"
                           },
                           {  
                              "code":"5.nf.4b"
                           }
                        ]
                     },
                     {  
                        "code":"5.nf.5",
                        "children":[  
                           {  
                              "code":"5.nf.5a"
                           },
                           {  
                              "code":"5.nf.5b"
                           }
                        ]
                     },
                     {  
                        "code":"5.nf.6"
                     },
                     {  
                        "code":"5.nf.7",
                        "children":[  
                           {  
                              "code":"5.nf.7a"
                           },
                           {  
                              "code":"5.nf.7b"
                           },
                           {  
                              "code":"5.nf.7c"
                           }
                        ]
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Road to Algebra",
            "code":"oa",
            "clusters":[  
               {  
                  "name":"Expressions with parenthesis",
                  "standards":[  
                     {  
                        "code":"5.oa.1"
                     },
                     {  
                        "code":"5.oa.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Patterns",
                  "standards":[  
                     {  
                        "code":"5.oa.3"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Place Value",
            "code":"nbt",
            "clusters":[  
               {  
                  "name":"Understanding place value",
                  "standards":[  
                     {  
                        "code":"5.nbt.1"
                     },
                     {  
                        "code":"5.nbt.2"
                     },
                     {  
                        "code":"5.nbt.3",
                        "children":[  
                           {  
                              "code":"5.nbt.3a"
                           },
                           {  
                              "code":"5.nbt.3b"
                           }
                        ]
                     },
                     {  
                        "code":"5.nbt.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Operations",
                  "standards":[  
                     {  
                        "code":"5.nbt.5"
                     },
                     {  
                        "code":"5.nbt.6"
                     },
                     {  
                        "code":"5.nbt.7"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Measurement and Data",
            "code":"md",
            "clusters":[  
               {  
                  "name":"Units",
                  "standards":[  
                     {  
                        "code":"5.md.1"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Data",
                  "standards":[  
                     {  
                        "code":"5.md.2"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Volume",
                  "standards":[  
                     {  
                        "code":"5.md.3",
                        "children":[  
                           {  
                              "code":"5.md.3a"
                           },
                           {  
                              "code":"5.md.3b"
                           }
                        ]
                     },
                     {  
                        "code":"5.md.4"
                     },
                     {  
                        "code":"5.md.5",
                        "children":[  
                           {  
                              "code":"5.md.5a"
                           },
                           {  
                              "code":"5.md.5b"
                           },
                           {  
                              "code":"5.md.5c"
                           }
                        ]
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Graph points",
                  "standards":[  
                     {  
                        "code":"5.g.1"
                     },
                     {  
                        "code":"5.g.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Shape classification",
                  "standards":[  
                     {  
                        "code":"5.g.3"
                     },
                     {  
                        "code":"5.g.4"
                     }
                  ],
                  "index":"b"
               }
            ]
         }
      ]
   },
   {  
      "name":"6<sup>th</sup> Grade",
      "strands":[  
         {  
            "name":"Ratios and Proportions",
            "code":"rp",
            "clusters":[  
               {  
                  "name":"Ratios",
                  "standards":[  
                     {  
                        "code":"6.rp.1"
                     },
                     {  
                        "code":"6.rp.2"
                     },
                     {  
                        "code":"6.rp.3",
                        "children":[  
                           {  
                              "code":"6.rp.3a"
                           },
                           {  
                              "code":"6.rp.3b"
                           },
                           {  
                              "code":"6.rp.3c"
                           },
                           {  
                              "code":"6.rp.3d"
                           }
                        ]
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Expressions and Equations",
            "code":"ee",
            "clusters":[  
               {  
                  "name":"Expressions",
                  "standards":[  
                     {  
                        "code":"6.ee.1"
                     },
                     {  
                        "code":"6.ee.2",
                        "children":[  
                           {  
                              "code":"6.ee.2a"
                           },
                           {  
                              "code":"6.ee.2b"
                           },
                           {  
                              "code":"6.ee.2c"
                           }
                        ]
                     },
                     {  
                        "code":"6.ee.3"
                     },
                     {  
                        "code":"6.ee.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"One-variable relationships",
                  "standards":[  
                     {  
                        "code":"6.ee.5"
                     },
                     {  
                        "code":"6.ee.6"
                     },
                     {  
                        "code":"6.ee.7"
                     },
                     {  
                        "code":"6.ee.8"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Two-variable relationships",
                  "standards":[  
                     {  
                        "code":"6.ee.9"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"The Number System",
            "code":"ns",
            "clusters":[  
               {  
                  "name":"Fraction operations",
                  "standards":[  
                     {  
                        "code":"6.ns.1"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Operate fluently",
                  "standards":[  
                     {  
                        "code":"6.ns.2"
                     },
                     {  
                        "code":"6.ns.3"
                     },
                     {  
                        "code":"6.ns.4"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Negative nubers",
                  "standards":[  
                     {  
                        "code":"6.ns.5"
                     },
                     {  
                        "code":"6.ns.6",
                        "children":[  
                           {  
                              "code":"6.ns.6a"
                           },
                           {  
                              "code":"6.ns.6b"
                           },
                           {  
                              "code":"6.ns.6c"
                           }
                        ]
                     },
                     {  
                        "code":"6.ns.7",
                        "children":[  
                           {  
                              "code":"6.ns.7a"
                           },
                           {  
                              "code":"6.ns.7b"
                           },
                           {  
                              "code":"6.ns.7c"
                           },
                           {  
                              "code":"6.ns.7d"
                           }
                        ]
                     },
                     {  
                        "code":"6.ns.8"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Statistics and Probability",
            "code":"sp",
            "clusters":[  
               {  
                  "name":"Variability and center",
                  "standards":[  
                     {  
                        "code":"6.sp.1"
                     },
                     {  
                        "code":"6.sp.2"
                     },
                     {  
                        "code":"6.sp.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Distributions",
                  "standards":[  
                     {  
                        "code":"6.sp.4"
                     },
                     {  
                        "code":"6.sp.5",
                        "children":[  
                           {  
                              "code":"6.sp.5a"
                           },
                           {  
                              "code":"6.sp.5b"
                           },
                           {  
                              "code":"6.sp.5c"
                           },
                           {  
                              "code":"6.sp.5d"
                           }
                        ]
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Area and volume",
                  "standards":[  
                     {  
                        "code":"6.g.1"
                     },
                     {  
                        "code":"6.g.2"
                     },
                     {  
                        "code":"6.g.3"
                     },
                     {  
                        "code":"6.g.4"
                     }
                  ],
                  "index":"a"
               }
            ]
         }
      ]
   },
   {  
      "name":"7<sup>th</sup> Grade",
      "strands":[  
         {  
            "name":"Ratios and Proportions",
            "code":"rp",
            "clusters":[  
               {  
                  "name":"Proportional relationships",
                  "standards":[  
                     {  
                        "code":"7.rp.1"
                     },
                     {  
                        "code":"7.rp.2",
                        "children":[  
                           {  
                              "code":"7.rp.2a"
                           },
                           {  
                              "code":"7.rp.2b"
                           },
                           {  
                              "code":"7.rp.2c"
                           },
                           {  
                              "code":"7.rp.2d"
                           }
                        ]
                     },
                     {  
                        "code":"7.rp.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Expressions and Equations",
            "code":"ee",
            "clusters":[  
               {  
                  "name":"Equivalent expressions",
                  "standards":[  
                     {  
                        "code":"7.ee.1"
                     },
                     {  
                        "code":"7.ee.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Problem solving",
                  "standards":[  
                     {  
                        "code":"7.ee.3"
                     },
                     {  
                        "code":"7.ee.4",
                        "children":[  
                           {  
                              "code":"7.ee.4a"
                           },
                           {  
                              "code":"7.ee.4b"
                           }
                        ]
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"The Number System",
            "code":"ns",
            "clusters":[  
               {  
                  "name":"Rational nubers",
                  "standards":[  
                     {  
                        "code":"7.ns.1",
                        "children":[  
                           {  
                              "code":"7.ns.1a"
                           },
                           {  
                              "code":"7.ns.1b"
                           },
                           {  
                              "code":"7.ns.1c"
                           },
                           {  
                              "code":"7.ns.1d"
                           }
                        ]
                     },
                     {  
                        "code":"7.ns.2",
                        "children":[  
                           {  
                              "code":"7.ns.2a"
                           },
                           {  
                              "code":"7.ns.2b"
                           },
                           {  
                              "code":"7.ns.2c"
                           },
                           {  
                              "code":"7.ns.2d"
                           }
                        ]
                     },
                     {  
                        "code":"7.ns.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Statistics and Probability",
            "code":"sp",
            "clusters":[  
               {  
                  "name":"Sampling",
                  "standards":[  
                     {  
                        "code":"7.sp.1"
                     },
                     {  
                        "code":"7.sp.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Comparative inferences",
                  "standards":[  
                     {  
                        "code":"7.sp.3"
                     },
                     {  
                        "code":"7.sp.4"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Probability",
                  "standards":[  
                     {  
                        "code":"7.sp.5"
                     },
                     {  
                        "code":"7.sp.6"
                     },
                     {  
                        "code":"7.sp.7",
                        "children":[  
                           {  
                              "code":"7.sp.7a"
                           },
                           {  
                              "code":"7.sp.7b"
                           }
                        ]
                     },
                     {  
                        "code":"7.sp.8",
                        "children":[  
                           {  
                              "code":"7.sp.8a"
                           },
                           {  
                              "code":"7.sp.8b"
                           },
                           {  
                              "code":"7.sp.8c"
                           }
                        ]
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Geometric figures",
                  "standards":[  
                     {  
                        "code":"7.g.1"
                     },
                     {  
                        "code":"7.g.2"
                     },
                     {  
                        "code":"7.g.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Geometry problems",
                  "standards":[  
                     {  
                        "code":"7.g.4"
                     },
                     {  
                        "code":"7.g.5"
                     },
                     {  
                        "code":"7.g.6"
                     }
                  ],
                  "index":"b"
               }
            ]
         }
      ]
   },
   {  
      "name":"8<sup>th</sup> Grade",
      "strands":[  
         {  
            "name":"Functions",
            "code":"f",
            "clusters":[  
               {  
                  "name":"Understand functions",
                  "standards":[  
                     {  
                        "code":"8.f.1"
                     },
                     {  
                        "code":"8.f.2"
                     },
                     {  
                        "code":"8.f.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Model with functions",
                  "standards":[  
                     {  
                        "code":"8.f.4"
                     },
                     {  
                        "code":"8.f.5"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Expressions and Equations",
            "code":"ee",
            "clusters":[  
               {  
                  "name":"Exponents",
                  "standards":[  
                     {  
                        "code":"8.ee.1"
                     },
                     {  
                        "code":"8.ee.2"
                     },
                     {  
                        "code":"8.ee.3"
                     },
                     {  
                        "code":"8.ee.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Linearity and proportionality",
                  "standards":[  
                     {  
                        "code":"8.ee.5"
                     },
                     {  
                        "code":"8.ee.6"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Linear equations",
                  "standards":[  
                     {  
                        "code":"8.ee.7",
                        "children":[  
                           {  
                              "code":"8.ee.7a"
                           },
                           {  
                              "code":"8.ee.7b"
                           }
                        ]
                     },
                     {  
                        "code":"8.ee.8",
                        "children":[  
                           {  
                              "code":"8.ee.8a"
                           },
                           {  
                              "code":"8.ee.8b"
                           },
                           {  
                              "code":"8.ee.8c"
                           }
                        ]
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"The Number System",
            "code":"ns",
            "clusters":[  
               {  
                  "name":"Irrational numbers",
                  "standards":[  
                     {  
                        "code":"8.ns.1"
                     },
                     {  
                        "code":"8.ns.2"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Statistics and Probability",
            "code":"sp",
            "clusters":[  
               {  
                  "name":"Bivariate data",
                  "standards":[  
                     {  
                        "code":"8.sp.1"
                     },
                     {  
                        "code":"8.sp.2"
                     },
                     {  
                        "code":"8.sp.3"
                     },
                     {  
                        "code":"8.sp.4"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Geometry",
            "code":"g",
            "clusters":[  
               {  
                  "name":"Congruence and similarity",
                  "standards":[  
                     {  
                        "code":"8.g.1",
                        "children":[  
                           {  
                              "code":"8.g.1a"
                           },
                           {  
                              "code":"8.g.1b"
                           },
                           {  
                              "code":"8.g.1c"
                           }
                        ]
                     },
                     {  
                        "code":"8.g.2"
                     },
                     {  
                        "code":"8.g.3"
                     },
                     {  
                        "code":"8.g.4"
                     },
                     {  
                        "code":"8.g.5"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"Pythagorean theorem",
                  "standards":[  
                     {  
                        "code":"8.g.6"
                     },
                     {  
                        "code":"8.g.7"
                     },
                     {  
                        "code":"8.g.8"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"Volume",
                  "standards":[  
                     {  
                        "code":"8.g.9"
                     }
                  ],
                  "index":"c"
               }
            ]
         }
      ]
   },
   {  
      "name":"Functions",
      "strands":[  
         {  
            "name":"Interpreting Functions",
            "code":"if",
            "clusters":[  
               {  
                  "name":"understand functions",
                  "standards":[  
                     {  
                        "code":"hsf.if.1"
                     },
                     {  
                        "code":"hsf.if.2"
                     },
                     {  
                        "code":"hsf.if.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"interpret functions",
                  "standards":[  
                     {  
                        "code":"hsf.if.4"
                     },
                     {  
                        "code":"hsf.if.5"
                     },
                     {  
                        "code":"hsf.if.6"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"function representations",
                  "standards":[  
                     {  
                        "code":"hsf.if.7",
                        "children":[  
                           {  
                              "code":"hsf.if.7a"
                           },
                           {  
                              "code":"hsf.if.7b"
                           },
                           {  
                              "code":"hsf.if.7c"
                           },
                           {  
                              "code":"hsf.if.7d"
                           },
                           {  
                              "code":"hsf.if.7e"
                           }
                        ]
                     },
                     {  
                        "code":"hsf.if.8",
                        "children":[  
                           {  
                              "code":"hsf.if.8a"
                           },
                           {  
                              "code":"hsf.if.8b"
                           }
                        ]
                     },
                     {  
                        "code":"hsf.if.9"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Building Functions",
            "code":"bf",
            "clusters":[  
               {  
                  "name":"model with functions",
                  "standards":[  
                     {  
                        "code":"hsf.bf.1",
                        "children":[  
                           {  
                              "code":"hsf.bf.1a"
                           },
                           {  
                              "code":"hsf.bf.1b"
                           },
                           {  
                              "code":"hsf.bf.1c"
                           }
                        ]
                     },
                     {  
                        "code":"hsf.bf.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"model with functions",
                  "standards":[  
                     {  
                        "code":"hsf.bf.3"
                     },
                     {  
                        "code":"hsf.bf.4",
                        "children":[  
                           {  
                              "code":"hsf.bf.4a"
                           },
                           {  
                              "code":"hsf.bf.4b"
                           },
                           {  
                              "code":"hsf.bf.4c"
                           },
                           {  
                              "code":"hsf.bf.4d"
                           }
                        ]
                     },
                     {  
                        "code":"hsf.bf.5"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Linear and Exponential Models",
            "code":"le",
            "clusters":[  
               {  
                  "name":"construct models",
                  "standards":[  
                     {  
                        "code":"hsf.le.1",
                        "children":[  
                           {  
                              "code":"hsf.le.1a"
                           },
                           {  
                              "code":"hsf.le.1b"
                           },
                           {  
                              "code":"hsf.le.1c"
                           }
                        ]
                     },
                     {  
                        "code":"hsf.le.2"
                     },
                     {  
                        "code":"hsf.le.3"
                     },
                     {  
                        "code":"hsf.le.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"interpret expressions",
                  "standards":[  
                     {  
                        "code":"hsf.le.5"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Trigonometric Functions",
            "code":"tf",
            "clusters":[  
               {  
                  "name":"unit circle trig",
                  "standards":[  
                     {  
                        "code":"hsf.tf.1"
                     },
                     {  
                        "code":"hsf.tf.2"
                     },
                     {  
                        "code":"hsf.tf.3"
                     },
                     {  
                        "code":"hsf.tf.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"model with trig functions",
                  "standards":[  
                     {  
                        "code":"hsf.tf.5"
                     },
                     {  
                        "code":"hsf.tf.6"
                     },
                     {  
                        "code":"hsf.tf.7"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"graphs",
                  "standards":[  
                     {  
                        "code":"hsf.tf.8"
                     },
                     {  
                        "code":"hsf.tf.9"
                     }
                  ],
                  "index":"c"
               }
            ]
         }
      ]
   },
   {  
      "name":"Algebra",
      "strands":[  
         {  
            "name":"Structure in Expressions",
            "code":"sse",
            "clusters":[  
               {  
                  "name":"interpreting structure",
                  "standards":[  
                     {  
                        "code":"hsa.sse.1",
                        "children":[  
                           {  
                              "code":"hsa.sse.1a"
                           },
                           {  
                              "code":"hsa.sse.1b"
                           }
                        ]
                     },
                     {  
                        "code":"hsa.sse.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"rewrite and solve",
                  "standards":[  
                     {  
                        "code":"hsa.sse.3",
                        "children":[  
                           {  
                              "code":"hsa.sse.3a"
                           },
                           {  
                              "code":"hsa.sse.3b"
                           },
                           {  
                              "code":"hsa.sse.3c"
                           }
                        ]
                     },
                     {  
                        "code":"hsa.sse.4"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Polynomials and Rational Expressions",
            "code":"apr",
            "clusters":[  
               {  
                  "name":"work with polynomials",
                  "standards":[  
                     {  
                        "code":"hsa.apr.1"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"link zeros and factors",
                  "standards":[  
                     {  
                        "code":"hsa.apr.2"
                     },
                     {  
                        "code":"hsa.apr.3"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"polynomial identities",
                  "standards":[  
                     {  
                        "code":"hsa.apr.4"
                     },
                     {  
                        "code":"hsa.apr.5"
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"rewrite rational expressions",
                  "standards":[  
                     {  
                        "code":"hsa.apr.6"
                     },
                     {  
                        "code":"hsa.apr.7"
                     }
                  ],
                  "index":"d"
               }
            ]
         },
         {  
            "name":"Creating Equations",
            "code":"ced",
            "clusters":[  
               {  
                  "name":"create equations",
                  "standards":[  
                     {  
                        "code":"hsa.ced.1"
                     },
                     {  
                        "code":"hsa.ced.2"
                     },
                     {  
                        "code":"hsa.ced.3"
                     },
                     {  
                        "code":"hsa.ced.4"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Reasoning with Equations and Inequalities",
            "code":"rei",
            "clusters":[  
               {  
                  "name":"solve by reasoning",
                  "standards":[  
                     {  
                        "code":"hsa.rei.1"
                     },
                     {  
                        "code":"hsa.rei.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"1-variable relations",
                  "standards":[  
                     {  
                        "code":"hsa.rei.3"
                     },
                     {  
                        "code":"hsa.rei.4",
                        "children":[  
                           {  
                              "code":"hsa.rei.4a"
                           },
                           {  
                              "code":"hsa.rei.4b"
                           }
                        ]
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"systems of equations",
                  "standards":[  
                     {  
                        "code":"hsa.rei.5"
                     },
                     {  
                        "code":"hsa.rei.6"
                     },
                     {  
                        "code":"hsa.rei.7"
                     },
                     {  
                        "code":"hsa.rei.8"
                     },
                     {  
                        "code":"hsa.rei.9"
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"graphs",
                  "standards":[  
                     {  
                        "code":"hsa.rei.10"
                     },
                     {  
                        "code":"hsa.rei.11"
                     },
                     {  
                        "code":"hsa.rei.12"
                     }
                  ],
                  "index":"d"
               }
            ]
         }
      ]
   },
   {  
      "name":"Number and Quantity",
      "strands":[  
         {  
            "name":"Real Number System",
            "code":"rn",
            "clusters":[  
               {  
                  "name":"rational exponents",
                  "standards":[  
                     {  
                        "code":"hsn.rn.1"
                     },
                     {  
                        "code":"hsn.rn.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"rational vs irrational",
                  "standards":[  
                     {  
                        "code":"hsn.rn.3"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Quantities",
            "code":"q",
            "clusters":[  
               {  
                  "name":"reason quantitatively",
                  "standards":[  
                     {  
                        "code":"hsn.q.1"
                     },
                     {  
                        "code":"hsn.q.2"
                     },
                     {  
                        "code":"hsn.q.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         },
         {  
            "name":"Complex Numbers",
            "code":"cn",
            "clusters":[  
               {  
                  "name":"complex number operations",
                  "standards":[  
                     {  
                        "code":"hsn.cn.1"
                     },
                     {  
                        "code":"hsn.cn.2"
                     },
                     {  
                        "code":"hsn.cn.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"the complex plane",
                  "standards":[  
                     {  
                        "code":"hsn.cn.4"
                     },
                     {  
                        "code":"hsn.cn.5"
                     },
                     {  
                        "code":"hsn.cn.6"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"apply complex numbers",
                  "standards":[  
                     {  
                        "code":"hsn.cn.7"
                     },
                     {  
                        "code":"hsn.cn.8"
                     },
                     {  
                        "code":"hsn.cn.9"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Vectors and Matrices",
            "code":"vm",
            "clusters":[  
               {  
                  "name":"model with vectors",
                  "standards":[  
                     {  
                        "code":"hsn.vm.1"
                     },
                     {  
                        "code":"hsn.vm.2"
                     },
                     {  
                        "code":"hsn.vm.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"work with vectors",
                  "standards":[  
                     {  
                        "code":"hsn.vm.4",
                        "children":[  
                           {  
                              "code":"hsn.vm.4a"
                           },
                           {  
                              "code":"hsn.vm.4b"
                           },
                           {  
                              "code":"hsn.vm.4c"
                           }
                        ]
                     },
                     {  
                        "code":"hsn.vm.5",
                        "children":[  
                           {  
                              "code":"hsn.vm.5a"
                           },
                           {  
                              "code":"hsn.vm.5b"
                           }
                        ]
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"matrices",
                  "standards":[  
                     {  
                        "code":"hsn.vm.6"
                     },
                     {  
                        "code":"hsn.vm.7"
                     },
                     {  
                        "code":"hsn.vm.8"
                     },
                     {  
                        "code":"hsn.vm.9"
                     },
                     {  
                        "code":"hsn.vm.10"
                     },
                     {  
                        "code":"hsn.vm.11"
                     },
                     {  
                        "code":"hsn.vm.12"
                     }
                  ],
                  "index":"c"
               }
            ]
         }
      ]
   },
   {  
      "name":"Statistics and Probability",
      "strands":[  
         {  
            "name":"Interpreting Data",
            "code":"id",
            "clusters":[  
               {  
                  "name":"data on one variable",
                  "standards":[  
                     {  
                        "code":"hss.id.1"
                     },
                     {  
                        "code":"hss.id.2"
                     },
                     {  
                        "code":"hss.id.3"
                     },
                     {  
                        "code":"hss.id.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"data on two variables",
                  "standards":[  
                     {  
                        "code":"hss.id.5"
                     },
                     {  
                        "code":"hss.id.6",
                        "children":[  
                           {  
                              "code":"hss.id.6a"
                           },
                           {  
                              "code":"hss.id.6b"
                           },
                           {  
                              "code":"hss.id.6c"
                           }
                        ]
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"linear models",
                  "standards":[  
                     {  
                        "code":"hss.id.7"
                     },
                     {  
                        "code":"hss.id.8"
                     },
                     {  
                        "code":"hss.id.9"
                     }
                  ],
                  "index":"c"
               }
            ]
         },
         {  
            "name":"Inferences and Conclusions",
            "code":"ic",
            "clusters":[  
               {  
                  "name":"random processes",
                  "standards":[  
                     {  
                        "code":"hss.ic.1"
                     },
                     {  
                        "code":"hss.ic.2"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"inferences",
                  "standards":[  
                     {  
                        "code":"hss.ic.3"
                     },
                     {  
                        "code":"hss.ic.4"
                     },
                     {  
                        "code":"hss.ic.5"
                     },
                     {  
                        "code":"hss.ic.6"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Conditional Probability",
            "code":"cp",
            "clusters":[  
               {  
                  "name":"independent vs. conditional",
                  "standards":[  
                     {  
                        "code":"hss.cp.1"
                     },
                     {  
                        "code":"hss.cp.2"
                     },
                     {  
                        "code":"hss.cp.3"
                     },
                     {  
                        "code":"hss.cp.4"
                     },
                     {  
                        "code":"hss.cp.5"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"uniform probability models",
                  "standards":[  
                     {  
                        "code":"hss.cp.6"
                     },
                     {  
                        "code":"hss.cp.7"
                     },
                     {  
                        "code":"hss.cp.8"
                     },
                     {  
                        "code":"hss.cp.9"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Make Decisions",
            "code":"md",
            "clusters":[  
               {  
                  "name":"expected value",
                  "standards":[  
                     {  
                        "code":"hss.md.1"
                     },
                     {  
                        "code":"hss.md.2"
                     },
                     {  
                        "code":"hss.md.3"
                     },
                     {  
                        "code":"hss.md.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"model with trig functions",
                  "standards":[  
                     {  
                        "code":"hss.md.5",
                        "children":[  
                           {  
                              "code":"hss.md.5a"
                           },
                           {  
                              "code":"hss.md.5b"
                           }
                        ]
                     },
                     {  
                        "code":"hss.md.6"
                     },
                     {  
                        "code":"hss.md.7"
                     }
                  ],
                  "index":"b"
               }
            ]
         }
      ]
   },
   {  
      "name":"Geometry",
      "strands":[  
         {  
            "name":"Congruence",
            "code":"co",
            "clusters":[  
               {  
                  "name":"transformations",
                  "standards":[  
                     {  
                        "code":"hsg.co.1"
                     },
                     {  
                        "code":"hsg.co.2"
                     },
                     {  
                        "code":"hsg.co.3"
                     },
                     {  
                        "code":"hsg.co.4"
                     },
                     {  
                        "code":"hsg.co.5"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"congruence by rigid motions",
                  "standards":[  
                     {  
                        "code":"hsg.co.6"
                     },
                     {  
                        "code":"hsg.co.7"
                     },
                     {  
                        "code":"hsg.co.8"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"prove theorems",
                  "standards":[  
                     {  
                        "code":"hsg.co.9"
                     },
                     {  
                        "code":"hsg.co.10"
                     },
                     {  
                        "code":"hsg.co.11"
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"constructions",
                  "standards":[  
                     {  
                        "code":"hsg.co.12"
                     },
                     {  
                        "code":"hsg.co.13"
                     }
                  ],
                  "index":"d"
               }
            ]
         },
         {  
            "name":"Similarity, Right Triangles, and Trig",
            "code":"srt",
            "clusters":[  
               {  
                  "name":"similarity transformations",
                  "standards":[  
                     {  
                        "code":"hsg.srt.1",
                        "children":[  
                           {  
                              "code":"hsg.srt.1a"
                           },
                           {  
                              "code":"hsg.srt.1b"
                           }
                        ]
                     },
                     {  
                        "code":"hsg.srt.2"
                     },
                     {  
                        "code":"hsg.srt.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"similarity theorems",
                  "standards":[  
                     {  
                        "code":"hsg.srt.4"
                     },
                     {  
                        "code":"hsg.srt.5"
                     }
                  ],
                  "index":"b"
               },
               {  
                  "name":"right triangle trig",
                  "standards":[  
                     {  
                        "code":"hsg.srt.6"
                     },
                     {  
                        "code":"hsg.srt.7"
                     },
                     {  
                        "code":"hsg.srt.8"
                     }
                  ],
                  "index":"c"
               },
               {  
                  "name":"non-right triangle trig",
                  "standards":[  
                     {  
                        "code":"hsg.srt.9"
                     },
                     {  
                        "code":"hsg.srt.10"
                     },
                     {  
                        "code":"hsg.srt.11"
                     }
                  ],
                  "index":"d"
               }
            ]
         },
         {  
            "name":"Circle",
            "code":"c",
            "clusters":[  
               {  
                  "name":"circle-o theorems",
                  "standards":[  
                     {  
                        "code":"hsg.c.1"
                     },
                     {  
                        "code":"hsg.c.2"
                     },
                     {  
                        "code":"hsg.c.3"
                     },
                     {  
                        "code":"hsg.c.4"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"arcs and sectors",
                  "standards":[  
                     {  
                        "code":"hsg.c.5"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Equations",
            "code":"gpe",
            "clusters":[  
               {  
                  "name":"derive equations",
                  "standards":[  
                     {  
                        "code":"hsg.gpe.1"
                     },
                     {  
                        "code":"hsg.gpe.2"
                     },
                     {  
                        "code":"hsg.gpe.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"coordinate plane geometry",
                  "standards":[  
                     {  
                        "code":"hsg.gpe.4"
                     },
                     {  
                        "code":"hsg.gpe.5"
                     },
                     {  
                        "code":"hsg.gpe.6"
                     },
                     {  
                        "code":"hsg.gpe.7"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Measurement and Dimension",
            "code":"gmd",
            "clusters":[  
               {  
                  "name":"volume",
                  "standards":[  
                     {  
                        "code":"hsg.gmd.1"
                     },
                     {  
                        "code":"hsg.gmd.2"
                     },
                     {  
                        "code":"hsg.gmd.3"
                     }
                  ],
                  "index":"a"
               },
               {  
                  "name":"link 2D and 3D shapes",
                  "standards":[  
                     {  
                        "code":"hsg.gmd.4"
                     }
                  ],
                  "index":"b"
               }
            ]
         },
         {  
            "name":"Modeling with Geometry",
            "code":"mg",
            "clusters":[  
               {  
                  "name":"modeling",
                  "standards":[  
                     {  
                        "code":"hsg.mg.1"
                     },
                     {  
                        "code":"hsg.mg.2"
                     },
                     {  
                        "code":"hsg.mg.3"
                     }
                  ],
                  "index":"a"
               }
            ]
         }
      ]
   }
]
